using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace Patient_Record_Management_System
{
    public partial class My : Form
    {
        string patientCNIC;
        public My(string pCNIC)
        {
            InitializeComponent();
            patientCNIC = pCNIC;
        }

        private void My_Load(object sender, EventArgs e)
        {
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["PRMS"].ToString()))
            {
                string query = @"
                               SELECT 
                                   Patient.[Patient Name],
                                   Patient.[Age],
                                   Patient.[Gender],
                                   Patient.[Phone],
                                   Patient.[Diagnosis],
                                   Patient.[Prescription],
                                   Patient.[Visit Date],
                                   Doctor.[Doctor Name]

                               FROM Patient

                               INNER JOIN Doctor
                               ON Patient.[Doctor ID] = Doctor.[Doctor ID]

                               WHERE Patient.[Patient CNIC] = @CNIC";

                SqlCommand cmd = new SqlCommand(query, con);

                cmd.Parameters.AddWithValue("@CNIC", patientCNIC);

                try
                {
                    con.Open();

                    SqlDataReader reader = cmd.ExecuteReader();

                    if (reader.Read())
                    {
                        NameLabel.Text = reader["Patient Name"].ToString();
                        AgeLabel.Text = reader["Age"].ToString();
                        GenderLabel.Text = reader["Gender"].ToString();
                        PhoneLabel.Text = reader["Phone"].ToString();
                        DiagnosisLabel.Text = reader["Diagnosis"].ToString();
                        PrescriptionLabel.Text = reader["Prescription"].ToString();
                        VisitDateLabel.Text = Convert.ToDateTime(reader["Visit Date"]).ToShortDateString();
                        DoctorLabel.Text = reader["Doctor Name"].ToString();
                    }

                    reader.Close();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void PrintGuna2Button_Click(object sender, EventArgs e)
        {
            SaveFileDialog save = new SaveFileDialog();

            save.Filter = "PDF Files|*.pdf";
            save.Title = "Save Patient Record";
            save.FileName = "PatientRecord.pdf";

            if (save.ShowDialog() == DialogResult.OK)
            {
                try
                {
                    Document doc = new Document(PageSize.A4);

                    PdfWriter.GetInstance(doc, new FileStream(save.FileName, FileMode.Create));

                    doc.Open();

                    iTextSharp.text.Font titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 20);

                    iTextSharp.text.Font textFont = FontFactory.GetFont(FontFactory.HELVETICA, 14);

                    Paragraph title = new Paragraph("Patient Medical Record", titleFont);
                    title.Alignment = Element.ALIGN_CENTER;

                    doc.Add(title);
                    doc.Add(new Paragraph("\n"));

                    doc.Add(new Paragraph("Patient Name: " + NameLabel.Text, textFont));
                    doc.Add(new Paragraph("Age: " + AgeLabel.Text, textFont));
                    doc.Add(new Paragraph("Gender: " + GenderLabel.Text, textFont));
                    doc.Add(new Paragraph("Phone: " + PhoneLabel.Text, textFont));
                    doc.Add(new Paragraph("Diagnosis: " + DiagnosisLabel.Text, textFont));
                    doc.Add(new Paragraph("Prescription: " + PrescriptionLabel.Text, textFont));
                    doc.Add(new Paragraph("Visit Date: " + VisitDateLabel.Text, textFont));
                    doc.Add(new Paragraph("Doctor Name: " + DoctorLabel.Text, textFont));

                    doc.Add(new Paragraph("\n"));

                    Paragraph footer = new Paragraph("Generated by Patient Record Management System", textFont);
                    footer.Alignment = Element.ALIGN_CENTER;

                    doc.Add(footer);

                    doc.Close();

                    MessageBox.Show("PDF Saved Successfully!", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }
    }
}
